# Interview Questions from...
https://www.simplilearn.com/tutorials/machine-learning-tutorial/machine-learning-interview-questions



# How to avoid overfitting?
1. Regularization term added to loss function.  example.. ?
1. K-fold batches
1. Stopping training when validation starts to drop
1. Adding more data.

example?



# What to do with missing data fields?
* Set the value to something specific - mean/mode/median  (mean si average, median is value where number of ordinal categories above and below are the same).
* mode is the most common,

In [ ]:
# pandas...

isNul()
dropna()
fillna()


How can you choose a classifier based on training set data size?

Exaplain the confusion matrix...

* Confusion matrix involves two nominal variables (categorical variables)
* Confusion matrix colorizes (heatmaps) the correlation between two variables - red/white are closely correlated - blue/green are loosely correlated.


Given 12 individuals
8 diagnosed with cancer
4 are cancer free


           1  |  TP   FP     
predicted     |
           0  |  FN     TN   
               -------------
                 1    0
                  actual

In [38]:
import pandas as pd
import numpy as np

# df = pd.dataframe()
df1 = pd.DataFrame(np.random.randint(0,100,size=(5,5)))
df2 = pd.DataFrame(np.random.randint(0,3,size=(5,5)))
df3 = pd.DataFrame(np.identity(5, dtype=np.int8))
df_a = df1.multiply(df3).add(df2)
df_a

0   1   2   3   4
0  29   1   2   1   1
1   1  90   2   2   1
2   2   0  38   0   0
3   0   0   1  47   1
4   1   1   0   1  75

# Compare k-means to KNN

K-means is a clustering altorighm. The assumption is the data is selected from K gaussian distributions.
Thus it is characterized as k  means + std-deviations

KNN is K-nearest neighbor.
It is an iterative technique where k of the samples are chosen. Then 
df3

In [32]:
df1.multiply(df3)

0   1   2   3   4
0  30   0   0   0   0
1   0  66   0   0   0
2   0   0  58   0   0
3   0   0   0  46   0
4   0   0   0   0  37

In [16]:
df = pd.DataFrame(np.identity(5, dtype=np.int8))
df

0  1  2  3  4
0  1  0  0  0  0
1  0  1  0  0  0
2  0  0  1  0  0
3  0  0  0  1  0
4  0  0  0  0  1

# Precision and Recall   !!!! FIX THIS SHIT!

Precision = TP / (TP + FP)

Recall = TP / (TP = FN)

Precision/Recall curve demonstrates the P/R value for some value of 

In [42]:
# precision-recall curve and f1
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import f1_score
from sklearn.metrics import auc
from matplotlib import pyplot
# generate 2 class dataset
X, y = make_classification(n_samples=1000, n_classes=2, random_state=1)
# split into train/test sets
trainX, testX, trainy, testy = train_test_split(X, y, test_size=0.5, random_state=2)
# fit a model
model = LogisticRegression(solver='lbfgs')
model.fit(trainX, trainy)
# predict probabilities
lr_probs = model.predict_proba(testX)
# keep probabilities for the positive outcome only
lr_probs = lr_probs[:, 1]
# predict class values
yhat = model.predict(testX)
lr_precision, lr_recall, _ = precision_recall_curve(testy, lr_probs)
lr_f1, lr_auc = f1_score(testy, yhat), auc(lr_recall, lr_precision)
# summarize scores
print('Logistic: f1=%.3f auc=%.3f' % (lr_f1, lr_auc))
# plot the precision-recall curves
no_skill = len(testy[testy==1]) / len(testy)
# pyplot.plot([0, 1], [no_skill, no_skill], linestyle='--', label='No Skill')
# pyplot.plot(lr_recall, lr_precision, marker='.', label='Logistic')
# # axis labels
# pyplot.xlabel('Recall')
# pyplot.ylabel('Precision')
# # show the legend
# pyplot.legend()
# # show the plot
# pyplot.show()

Logistic: f1=0.841 auc=0.898


In [63]:
# generate 2 class dataset
X, y = make_classification(n_samples=1000, n_classes=2, random_state=1)
# split into train/test sets
trainX, testX, trainy, testy = train_test_split(X, y, test_size=0.5, random_state=2)
# fit a model
model = LogisticRegression(solver='lbfgs')
model.fit(trainX, trainy)
# predict probabilities
lr_probs = model.predict_proba(testX)
# keep probabilities for the positive outcome only
lr_probs = lr_probs[:, 1]
# predict class values
yhat = model.predict(testX)

In [69]:
testy.shape

(500,)

In [71]:
testy[0:20]

array([1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1])

In [67]:
lr_probs.shape

(500,)

In [64]:
lr_probs[0:5]

array([0.99597268, 0.99799484, 0.00529883, 0.15237419, 0.99833335])

In [68]:
yhat.shape

(500,)

In [72]:
yhat[0:20]


array([1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1])